version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  myRedis:
    image: myredis
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - redis